language: perl

install:
  - cpanm -n FFI::Platypus
  - cpanm -n ExtUtils::CppGuess
  - cpanm -n FFI::ExtractSymbols
  - cpanm -n FFI::Platypus::Lang::CPP

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script: HARNESS_IS_VERBOSE=1 prove -lv t xt

sudo: false
